/**
 * Demo data: three realistic vehicles with local placeholder photos
 * (public/demo/shots – generated by scripts/generate-demo-assets.mjs).
 */
import type { Vehicle, VehiclePhoto } from "@/lib/domain/types";
import { DEFAULT_SHOT_TEMPLATE, getOrderedShots } from "@/lib/shots/shot-template";

/** Paths with this prefix are served from /public instead of IndexedDB. */
export const STATIC_PATH_PREFIX = "static:";

export interface StoredPhoto extends VehiclePhoto {
  archivedAt: string | null;
}

interface SeedVehicle {
  vehicle: Omit<Vehicle, "createdAt" | "updatedAt">;
  photoCount: number;
  daysAgo: number;
}

const SEED_VEHICLES: SeedVehicle[] = [
  {
    vehicle: {
      id: "5d0c6f1e-63a1-4c84-9a5f-0d5b3f2c6301",
      userId: "demo-user",
      manufacturer: "Mercedes-Benz",
      model: "S 63 AMG",
      color: "Obsidianschwarz metallic",
      licensePlate: "SZ-AE 63",
      vin: "WDD2221861A123456",
      mileage: 48500,
      firstRegistration: "2021-03-15",
      internalReference: "FZ-2041",
      notes: "Panoramadach, Burmester Soundsystem. Kleiner Steinschlag Frontscheibe rechts.",
      status: "complete",
    },
    photoCount: 15,
    daysAgo: 0,
  },
  {
    vehicle: {
      id: "8b7e2d44-0f5a-4b8e-b3c1-7f6a9e1d5402",
      userId: "demo-user",
      manufacturer: "BMW",
      model: "X5 xDrive30d",
      color: "Mineralweiß metallic",
      licensePlate: "HD-BX 530",
      vin: "WBACV610X0LH12345",
      mileage: 72300,
      firstRegistration: "2020-06-02",
      internalReference: "FZ-2042",
      notes: null,
      status: "capturing",
    },
    photoCount: 9,
    daysAgo: 1,
  },
  {
    vehicle: {
      id: "c3a9f5b2-7d1e-4f6a-8c2b-9e4d1a7b3603",
      userId: "demo-user",
      manufacturer: "Audi",
      model: "A6 Avant 40 TDI",
      color: "Daytonagrau",
      licensePlate: "MA-AU 640",
      vin: null,
      mileage: 39800,
      firstRegistration: "2022-01-20",
      internalReference: "FZ-2043",
      notes: "Anhängerkupplung elektrisch.",
      status: "capturing",
    },
    photoCount: 4,
    daysAgo: 4,
  },
];

export function buildSeedData(now: Date = new Date()): {
  vehicles: Vehicle[];
  photos: StoredPhoto[];
} {
  const shots = getOrderedShots(DEFAULT_SHOT_TEMPLATE);
  const vehicles: Vehicle[] = [];
  const photos: StoredPhoto[] = [];

  for (const seed of SEED_VEHICLES) {
    const created = new Date(now.getTime() - seed.daysAgo * 86_400_000 - 3_600_000);
    const createdAt = created.toISOString();
    vehicles.push({ ...seed.vehicle, createdAt, updatedAt: createdAt });

    shots.slice(0, seed.photoCount).forEach((shot, index) => {
      const takenAt = new Date(created.getTime() + (index + 1) * 60_000).toISOString();
      const asset = `${STATIC_PATH_PREFIX}/demo/shots/${shot.key}.svg`;
      photos.push({
        id: `${seed.vehicle.id.slice(0, 24)}${String(index + 1).padStart(12, "0")}`,
        vehicleId: seed.vehicle.id,
        shotKey: shot.key,
        shotOrder: shot.order,
        title: shot.title,
        originalStoragePath: asset,
        processedStoragePath: null,
        processedPreset: null,
        thumbnailStoragePath: null,
        width: 1600,
        height: 1200,
        takenAt,
        createdAt: takenAt,
        updatedAt: takenAt,
        archivedAt: null,
      });
    });
  }

  return { vehicles, photos };
}
