"""Deterministic AutoExperten brand wall, composited onto the showroom BACKGROUND.

Nothing here is generated by AI:

- the logo is the official PNG from ``public/brand/official/`` – only trimmed
  to its alpha bounding box and scaled, its pixels/colours are never redrawn;
- "SCHWETZINGEN", the website and the phone number are typeset with the
  bundled Inter font (``fonts/``, SIL OFL 1.1).

The branding is applied to the empty showroom plate *before* the vehicle is
composited, so it can never be drawn over the vehicle. Every element has its
own, easy to tune position in the preset JSON (``branding`` section, all values
are fractions of the output width/height, see :class:`BrandingConfig`).

To look mounted rather than pasted, logo and city name get a soft contact
shadow on the wall (stand-off letters), and ``lightMatch`` lets the signage
follow the wall's own light falloff (brightness only – hue and saturation of
the logo stay exactly the official ones).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

import cv2
import numpy as np
from PIL import Image, ImageDraw, ImageFont

log = logging.getLogger(__name__)

FONT_DIR = Path(__file__).resolve().parent / "fonts"
FONT_FILES = {"semibold": "Inter-SemiBold.otf", "medium": "Inter-Medium.otf"}
#: Last resort if the bundled fonts are missing (searched in this order).
SYSTEM_FONT_CANDIDATES = (
    "/usr/share/fonts/opentype/inter/Inter-{Weight}.otf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
)

#: Text is rendered at this multiple of the target size and then downsampled.
SUPERSAMPLE = 3


class BrandingAssetError(Exception):
    """A configured branding asset (the official logo) cannot be loaded."""


@dataclass(frozen=True)
class LogoConfig:
    #: Official logo file, relative to the brand directory.
    file: str = "official/AutoExperten_Logo.png"
    #: Horizontal centre of the logo (fraction of the width).
    center_x: float = 0.5
    #: Top edge of the logo (fraction of the height).
    top: float = 0.07
    #: Maximum logo width / height (fractions of width / height); the smaller wins.
    max_width: float = 0.30
    max_height: float = 0.08
    opacity: float = 1.0
    #: Stand-off letters with a soft contact shadow on the wall.
    mounted: bool = True


@dataclass(frozen=True)
class TextConfig:
    text: str = ""
    center_x: float = 0.5
    #: Top of the capital letters (fraction of the height).
    top: float = 0.0
    #: Height of the capital letters (fraction of the height).
    cap_height: float = 0.012
    #: Extra letter spacing in em.
    tracking: float = 0.0
    #: sRGB hex colour, e.g. "#403F3F".
    color: str = "#403F3F"
    opacity: float = 1.0
    #: "semibold" or "medium" (bundled Inter weights).
    weight: str = "medium"
    mounted: bool = False


@dataclass(frozen=True)
class MountConfig:
    """Soft contact shadow of mounted signage (fractions of the height)."""

    shadow_opacity: float = 0.28
    shadow_offset: float = 0.0016
    shadow_blur: float = 0.0022


@dataclass(frozen=True)
class BrandingConfig:
    enabled: bool = True
    #: Free space (fraction of the height) the vehicle keeps below the branding.
    clearance: float = 0.03
    #: 0 = flat colours; 1 = signage brightness follows the wall light fully
    #: (darkening only, at most 15 %; hue/saturation unchanged).
    light_match: float = 0.5
    logo: LogoConfig = field(default_factory=LogoConfig)
    city: TextConfig = field(
        default_factory=lambda: TextConfig(
            text="SCHWETZINGEN", top=0.158, cap_height=0.0165, tracking=0.42, weight="semibold", mounted=True
        )
    )
    website: TextConfig = field(
        default_factory=lambda: TextConfig(
            text="www.autoexperten-rn.de", top=0.197, cap_height=0.0105, tracking=0.04, color="#4A4949"
        )
    )
    phone: TextConfig = field(
        default_factory=lambda: TextConfig(
            text="+49 6202 9262357", top=0.222, cap_height=0.0105, tracking=0.04, color="#4A4949"
        )
    )
    mount: MountConfig = field(default_factory=MountConfig)


@dataclass(frozen=True)
class BrandingLayout:
    """Where the branding ended up (pixels of the output frame)."""

    #: (name, x0, y0, x1, y1) per drawn element.
    boxes: tuple[tuple[str, int, int, int, int], ...]

    @property
    def bottom(self) -> int:
        return max((b[4] for b in self.boxes), default=0)

    def box(self, name: str) -> tuple[int, int, int, int] | None:
        for b in self.boxes:
            if b[0] == name:
                return b[1:]
        return None


# --------------------------------------------------------------------------- colour


def _srgb_to_linear(c: np.ndarray) -> np.ndarray:
    c = np.asarray(c, np.float32)
    return np.where(c <= 0.04045, c / 12.92, ((c + 0.055) / 1.055) ** 2.4).astype(np.float32)


def _linear_to_srgb_u8(c: np.ndarray) -> np.ndarray:
    c = np.clip(c, 0.0, 1.0)
    s = np.where(c <= 0.0031308, c * 12.92, 1.055 * np.power(c, 1 / 2.4) - 0.055)
    return np.clip(s * 255.0 + 0.5, 0, 255).astype(np.uint8)


def _hex_to_linear(value: str) -> np.ndarray:
    value = value.strip().lstrip("#")
    if len(value) != 6:
        raise ValueError(f"invalid colour '{value}'")
    rgb = np.array([int(value[i : i + 2], 16) for i in (0, 2, 4)], np.float32) / 255.0
    return _srgb_to_linear(rgb)


# --------------------------------------------------------------------------- assets


def logo_stamp(path: Path) -> int:
    """mtime of the logo file (0 if missing) – part of the background cache key."""
    try:
        return path.stat().st_mtime_ns
    except OSError:
        return 0


def _official_logo(path: Path) -> tuple[np.ndarray, np.ndarray]:
    """Official logo trimmed to its alpha bbox: (linear premultiplied RGB, alpha).

    Raises BrandingAssetError if the file is missing or unreadable – listing
    photos must never silently go out without the official logo.
    """
    stamp = logo_stamp(path)
    if stamp == 0:
        raise BrandingAssetError(f"official logo missing: {path}")
    return _load_logo(str(path), stamp)


@lru_cache(maxsize=4)
def _load_logo(path: str, _stamp: int) -> tuple[np.ndarray, np.ndarray]:
    try:
        with Image.open(path) as image:
            rgba = np.asarray(image.convert("RGBA"), np.float32) / 255.0
    except (OSError, ValueError) as error:
        raise BrandingAssetError(f"official logo unreadable: {path}: {error}") from None
    alpha = rgba[..., 3]
    ys, xs = np.nonzero(alpha > 8.0 / 255.0)
    if len(ys) == 0:
        raise BrandingAssetError(f"official logo is empty: {path}")
    rgba = rgba[ys.min() : ys.max() + 1, xs.min() : xs.max() + 1]
    alpha = np.ascontiguousarray(rgba[..., 3])
    premul = np.ascontiguousarray(_srgb_to_linear(rgba[..., :3]) * alpha[..., None])
    return premul, alpha


@lru_cache(maxsize=16)
def _font(weight: str, size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    name = FONT_FILES.get(weight, FONT_FILES["medium"])
    candidates = [FONT_DIR / name] + [
        Path(c.replace("{Weight}", "SemiBold" if weight == "semibold" else "Medium")) for c in SYSTEM_FONT_CANDIDATES
    ]
    for path in candidates:
        if path.is_file():
            try:
                # BASIC layout everywhere: identical glyph placement with or without
                # libraqm (the Docker image has none), no environment-dependent kerning
                return ImageFont.truetype(str(path), size, layout_engine=ImageFont.Layout.BASIC)
            except OSError:
                continue
    log.warning("Branding: no TrueType font found – falling back to Pillow's default font")
    return ImageFont.load_default(size)


def _cap_ratio(font) -> float:
    try:
        x0, y0, x1, y1 = font.getbbox("H")
        size = getattr(font, "size", 0) or 1
        return max((y1 - y0) / size, 0.3)
    except Exception:  # pragma: no cover - bitmap fallback font
        return 0.7


def _text_mask(cfg: TextConfig, height: int) -> np.ndarray | None:
    """Anti-aliased coverage mask of the text, cap height = cfg.cap_height * height."""
    text = cfg.text.strip()
    if not text:
        return None
    cap_px = max(4.0, cfg.cap_height * height) * SUPERSAMPLE
    probe = _font(cfg.weight, 100)
    size = max(4, int(round(cap_px / _cap_ratio(probe))))
    font = _font(cfg.weight, size)
    tracking_px = cfg.tracking * size
    # advance widths of the BASIC layout + tracking per glyph
    positions = [font.getlength(text[:i]) + i * tracking_px for i in range(len(text))]
    width = int(np.ceil(font.getlength(text) + max(len(text) - 1, 0) * tracking_px)) + 4 * SUPERSAMPLE
    ascent, descent = font.getmetrics()
    canvas = Image.new("L", (width, ascent + descent + 4 * SUPERSAMPLE), 0)
    draw = ImageDraw.Draw(canvas)
    for x, char in zip(positions, text):
        draw.text((x + 2 * SUPERSAMPLE, 2 * SUPERSAMPLE), char, fill=255, font=font)
    mask = np.asarray(canvas, np.float32) / 255.0
    ys, xs = np.nonzero(mask > 0.002)
    if len(ys) == 0:
        return None
    # crop so that the top of the mask is the top of the capitals
    cap_top = 2 * SUPERSAMPLE + font.getbbox("H")[1]
    mask = mask[min(cap_top, ys.min()) : ys.max() + 1, xs.min() : xs.max() + 1]
    out_w = max(1, int(round(mask.shape[1] / SUPERSAMPLE)))
    out_h = max(1, int(round(mask.shape[0] / SUPERSAMPLE)))
    return np.clip(cv2.resize(mask, (out_w, out_h), interpolation=cv2.INTER_AREA), 0.0, 1.0)


# --------------------------------------------------------------------------- compositing


@dataclass
class _Element:
    name: str
    premul: np.ndarray  # linear, premultiplied, (h, w, 3)
    alpha: np.ndarray  # (h, w)
    x: int
    y: int
    mounted: bool


def _logo_element(cfg: LogoConfig, brand_dir: Path, width: int, height: int) -> _Element | None:
    premul, alpha = _official_logo(brand_dir / cfg.file)
    lh, lw = alpha.shape
    scale = min(cfg.max_width * width / lw, cfg.max_height * height / lh)
    tw, th = max(2, int(round(lw * scale))), max(2, int(round(lh * scale)))
    interpolation = cv2.INTER_AREA if scale < 1.0 else cv2.INTER_LANCZOS4
    premul = cv2.resize(premul, (tw, th), interpolation=interpolation)
    alpha = np.clip(cv2.resize(alpha, (tw, th), interpolation=interpolation), 0.0, 1.0)
    premul = np.clip(premul, 0.0, alpha[..., None])  # no ringing beyond the official colours
    opacity = float(np.clip(cfg.opacity, 0.0, 1.0))
    x = int(round(cfg.center_x * width - tw / 2.0))
    y = int(round(cfg.top * height))
    return _Element("logo", premul * opacity, alpha * opacity, x, y, cfg.mounted)


def _text_element(name: str, cfg: TextConfig, width: int, height: int) -> _Element | None:
    mask = _text_mask(cfg, height)
    if mask is None:
        return None
    opacity = float(np.clip(cfg.opacity, 0.0, 1.0))
    alpha = mask * opacity
    premul = alpha[..., None] * _hex_to_linear(cfg.color)[None, None, :]
    x = int(round(cfg.center_x * width - mask.shape[1] / 2.0))
    y = int(round(cfg.top * height))
    return _Element(name, premul.astype(np.float32), alpha.astype(np.float32), x, y, cfg.mounted)


def _clip(element: _Element, width: int, height: int):
    h, w = element.alpha.shape
    x0, y0 = max(element.x, 0), max(element.y, 0)
    x1, y1 = min(element.x + w, width), min(element.y + h, height)
    if x1 <= x0 or y1 <= y0:
        return None
    sx, sy = x0 - element.x, y0 - element.y
    return x0, y0, x1, y1, sx, sy


def _elements(cfg: BrandingConfig, brand_dir: Path, width: int, height: int) -> list[_Element]:
    return [
        e
        for e in (
            _logo_element(cfg.logo, brand_dir, width, height),
            _text_element("city", cfg.city, width, height),
            _text_element("website", cfg.website, width, height),
            _text_element("phone", cfg.phone, width, height),
        )
        if e is not None
    ]


def _band(cfg: BrandingConfig, elements: list[_Element], height: int) -> int:
    """Rows that contain the branding (plus shadow and light-map margins)."""
    sigma = max(2.0, 0.02 * height)
    return min(height, max(e.y + e.alpha.shape[0] for e in elements) + _shadow_pad(cfg, height) + int(3 * sigma) + 1)


def _shadow_pad(cfg: BrandingConfig, height: int) -> int:
    mount = cfg.mount
    return int(np.ceil(4 * mount.shadow_blur * height + abs(mount.shadow_offset) * height)) + 2


def _composite(linear: np.ndarray, cfg: BrandingConfig, elements: list[_Element], height: int) -> list[tuple]:
    """Composite the elements into the LINEAR band `linear` (rows 0..band) in place."""
    band, width = linear.shape[:2]
    mount = cfg.mount
    sigma = max(2.0, 0.02 * height)
    shadow_pad = _shadow_pad(cfg, height)
    # Wall light around the branding (brightness only), used by lightMatch;
    # computed on a 4x smaller luminance map (it is very smooth anyway).
    light = None
    if cfg.light_match > 0:
        luminance = linear @ np.array([0.2126, 0.7152, 0.0722], np.float32)
        small = cv2.resize(luminance, (max(1, width // 4), max(1, band // 4)), interpolation=cv2.INTER_AREA)
        small = cv2.GaussianBlur(small, (0, 0), max(0.5, sigma / 4))
        light = cv2.resize(small, (width, band), interpolation=cv2.INTER_LINEAR)

    boxes = []
    for element in elements:
        clipped = _clip(element, width, band)
        if clipped is None:
            continue
        x0, y0, x1, y1, sx, sy = clipped
        alpha = element.alpha[sy : sy + (y1 - y0), sx : sx + (x1 - x0)]
        premul = element.premul[sy : sy + (y1 - y0), sx : sx + (x1 - x0)]

        if element.mounted and mount.shadow_opacity > 0:
            pad = shadow_pad
            sx0, sy0 = max(x0 - pad, 0), max(y0 - pad, 0)
            sx1, sy1 = min(x1 + pad, width), min(y1 + pad, band)
            shadow = np.zeros((sy1 - sy0, sx1 - sx0), np.float32)
            offset = int(round(mount.shadow_offset * height))
            ty0 = y0 - sy0 + offset  # may be < 0 for an upward offset at the top edge
            d0, d1 = max(ty0, 0), min(ty0 + alpha.shape[0], shadow.shape[0])
            if d1 > d0:
                shadow[d0:d1, x0 - sx0 : x0 - sx0 + alpha.shape[1]] = alpha[d0 - ty0 : d1 - ty0]
            shadow = cv2.GaussianBlur(shadow, (0, 0), max(0.8, mount.shadow_blur * height))
            linear[sy0:sy1, sx0:sx1] *= (1.0 - float(np.clip(mount.shadow_opacity, 0, 1)) * shadow)[..., None]

        if light is not None:
            region = light[y0:y1, x0:x1]
            reference = float(np.percentile(light[max(0, y0 - (y1 - y0)) : y1 + (y1 - y0), x0:x1], 90))
            factor = np.clip(region / max(reference, 1e-6), 0.85, 1.0)
            factor = 1.0 - float(np.clip(cfg.light_match, 0, 1)) * (1.0 - factor)
            premul = premul * factor[..., None]

        area = linear[y0:y1, x0:x1]
        linear[y0:y1, x0:x1] = premul + area * (1.0 - alpha[..., None])
        boxes.append((element.name, x0, y0, x1, y1))
    return boxes


def apply_branding(
    rgb: np.ndarray, cfg: BrandingConfig, brand_dir: Path
) -> tuple[np.ndarray, BrandingLayout]:
    """Return a branded copy of the sRGB uint8 image and the element boxes.

    Positions are fractions of this image's width/height. The showroom plates
    are branded in wall space instead (app/showroom/wall_branding.py), which
    runs this layout on a canvas that represents the brand wall.
    """
    height, width = rgb.shape[:2]
    if not cfg.enabled:
        return rgb, BrandingLayout(boxes=())
    elements = _elements(cfg, brand_dir, width, height)
    if not elements:
        return rgb, BrandingLayout(boxes=())
    # Only the band that contains the branding is processed; other rows are copied unchanged.
    band = _band(cfg, elements, height)
    if band <= 0:
        return rgb, BrandingLayout(boxes=())
    linear = _srgb_to_linear(rgb[:band].astype(np.float32) / 255.0)
    boxes = _composite(linear, cfg, elements, height)
    out = rgb.copy()
    out[:band] = _linear_to_srgb_u8(linear)
    return out, BrandingLayout(boxes=tuple(boxes))


def brand_uniform_band(
    value: tuple[float, float, float], width: int, height: int, cfg: BrandingConfig, brand_dir: Path
) -> tuple[np.ndarray, BrandingLayout] | None:
    """Brand a uniform LINEAR canvas of `width` × `height` filled with `value`.

    Only the band of rows that contains the branding (and its mount shadow) is
    built and returned (band × width × 3, float32) – every row below it would
    keep `value` exactly. None when nothing is drawn.
    """
    if not cfg.enabled:
        return None
    elements = _elements(cfg, brand_dir, width, height)
    if not elements:
        return None
    band = _band(cfg, elements, height)
    if band <= 0:
        return None
    linear = np.empty((band, width, 3), np.float32)
    linear[:] = np.asarray(value, np.float32)
    boxes = _composite(linear, cfg, elements, height)
    return linear, BrandingLayout(boxes=tuple(boxes))
